version: "3"

services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "8000:8000"
      - 8001:8001
      - 8002:8002
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    command: symfony server:start --no-tls
    depends_on:
      - db
  db:
    image: mariadb/server:10.4
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/symfony.cnf
      - ./logs:/var/log/mysql2
      - maria_db_10_4_mail5:/var/lib/mysql
  maildev:
    image: kanemu/maildev-with-iconv
    ports:
      - 8025:80
    command: bin/maildev -w 80 -s 25 --hide-extensions STARTTLS
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - 8033:80
    volumes:
      - "phpmyadminSession:/sessions"
volumes:
  phpmyadminSession:
  maria_db_10_4_mail5:
networks:
  default:
    driver: bridge
